apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: origin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - originbffp.example.com
    - port:
        name: grpc
        number: 50051
        protocol: TCP
      hosts:
        - originbffp.example.com

